from fortress_inventory.entity_graph import InventoryEntityGraph, InventoryEntityGraphError


GENERATED_CADDY_ROUTES_PATH = "/etc/caddy/fortress/generated-routes.caddy"
GENERATED_CADDY_LAYER4_ROUTES_PATH = "/etc/caddy/fortress/generated-layer4.caddy"
GENERATED_DNSMASQ_INGRESS_RECORDS_PATH = "pihole/etc-dnsmasq.d/99-fortress-ingress.conf"
GENERATED_FILE_HEADER = "# Generated by fortress ingress regeneration. Do not edit by hand."


def build_caddy_route_model(model):
    graph = InventoryEntityGraph(model)
    routes = []
    routes.extend(_service_routes(model, graph))
    routes.extend(_host_ingress_routes(model, graph))
    routes.extend(_nas_ingress_routes(model, graph))
    routes = sorted(routes, key=lambda route: route["hostname"])
    return {
        "ingress_address": _ingress_address(model, graph) if routes else None,
        "routes": routes,
    }


def build_caddy_layer4_route_model(model):
    graph = InventoryEntityGraph(model)
    routes = []
    routes.extend(_service_tcp_routes(model, graph))
    routes = sorted(routes, key=lambda route: (route["listen_address"], route["listen_port"], route["hostname"]))
    return {
        "routes": routes,
    }


def render_caddy_routes(model):
    route_model = build_caddy_route_model(model)
    return "\n\n".join(_render_caddy_route(route) for route in route_model["routes"]) + "\n"


def render_caddy_layer4_routes(model):
    route_model = build_caddy_layer4_route_model(model)
    if not route_model["routes"]:
        return GENERATED_FILE_HEADER + "\n"
    return "\n\n".join(_render_caddy_layer4_route(route) for route in route_model["routes"]) + "\n"


def render_ingress_dns_record_sets(model):
    route_model = build_caddy_route_model(model)
    layer4_route_model = build_caddy_layer4_route_model(model)
    content = _render_dnsmasq_ingress_records(route_model, layer4_route_model)
    return [
        {
            "service": target["service"],
            "provider": target["provider"],
            "backend_vm": target["backend_vm"],
            "path": f"/srv/services/{target['service']}/{GENERATED_DNSMASQ_INGRESS_RECORDS_PATH}",
            "write_mode": "replace",
            "content": content,
        }
        for target in ingress_dns_targets(model)
    ]


def ingress_dns_targets(model):
    graph = InventoryEntityGraph(model)
    targets = []
    for service_name, service in model.services.items():
        dns = service.get("dns") or {}
        if not dns.get("ingress_records", {}).get("enabled"):
            continue
        targets.append(
            {
                "service": service_name,
                "provider": dns.get("provider"),
                "backend_vm": graph.service_backend_vm_name(service_name),
            }
        )
    return sorted(targets, key=lambda target: target["service"])


def _render_dnsmasq_ingress_records(route_model, layer4_route_model):
    records = {}
    for route in route_model["routes"]:
        records.setdefault(route["hostname"], route_model["ingress_address"])
    for route in layer4_route_model["routes"]:
        records[route["hostname"]] = route["listen_address"]

    lines = [GENERATED_FILE_HEADER]
    for hostname, address in sorted(records.items()):
        lines.append(f"address=/{hostname}/{address}")
    return "\n".join(lines) + "\n"


def _service_routes(model, graph):
    routes = []
    for route in graph.service_ingress_route_facts():
        backend_vm_name = route.backend_vm_name
        if backend_vm_name not in model.vms:
            continue
        routes.append(
            {
                "kind": "service",
                "hostname": route.hostname,
                "target": _http_target(
                    _required_vm_static_ipv4_address(
                        graph,
                        backend_vm_name,
                        f"Backend VM {backend_vm_name}",
                    ),
                    route.published_port,
                ),
                "owner": route.service_name,
                "route": route.route_name,
                "tls": route.tls,
            }
        )
    return routes


def _service_tcp_routes(model, graph):
    routes = []
    for service_name, service in model.services.items():
        service_tcp_routes = service.get("ingress_tcp_routes", []) or []
        if not service_tcp_routes:
            continue
        backend_vm_name = graph.service_backend_vm_name(service_name)
        if backend_vm_name not in model.vms:
            continue
        backend_address = _required_vm_static_ipv4_address(
            graph,
            backend_vm_name,
            f"Backend VM {backend_vm_name}",
        )
        for route in service_tcp_routes:
            routes.append(
                {
                    "kind": "service_tcp",
                    "hostname": route["hostname"],
                    "listen_address": route["listen_address"],
                    "listen_port": route["listen_port"],
                    "target": f"{backend_address}:{route['published_port']}",
                    "owner": service_name,
                    "route": route["name"],
                }
            )
    return routes


def _host_ingress_routes(model, graph):
    routes = []
    trusted_source_ranges = _trusted_source_ranges(model)
    for host_name in graph.host_ingress_route_names():
        host = model.hosts[host_name]
        route = host.get("ingress", {}).get("proxmox_web_ui", {})
        routes.append(
            {
                "kind": "host",
                "hostname": route.get("hostname"),
                "target": _https_target(
                    _required_host_management_ipv4_address(
                        graph,
                        host_name,
                        f"Host Ingress Route {host_name}",
                    ),
                    route.get("port", 8006),
                ),
                "transport": "tls_insecure_skip_verify",
                "trusted_source_ranges": trusted_source_ranges,
                "owner": host_name,
                "tls": route.get("tls", "letsencrypt_dns"),
            }
        )
    return routes


def _nas_ingress_routes(model, graph):
    routes = []
    trusted_source_ranges = _trusted_source_ranges(model)
    for endpoint_name in graph.nas_ingress_route_names():
        endpoint = model.nas_endpoints[endpoint_name]
        route = endpoint.get("ingress", {}).get("web_ui", {})
        routes.append(
            {
                "kind": "nas",
                "hostname": route.get("hostname"),
                "target": _target(
                    route.get("scheme", "http"),
                    _required_nas_management_ipv4_address(
                        graph,
                        endpoint_name,
                        f"NAS Ingress Route {endpoint_name}",
                    ),
                    route.get("port", 80),
                ),
                "trusted_source_ranges": trusted_source_ranges,
                "owner": endpoint_name,
                "tls": route.get("tls", "letsencrypt_dns"),
            }
        )
    return routes


def _render_caddy_route(route):
    if route.get("trusted_source_ranges"):
        source_ranges = " ".join(route["trusted_source_ranges"])
        return "\n".join(
            [
                f"{route['hostname']} {{",
                _render_tls(route),
                f"\t@trusted remote_ip {source_ranges}",
                "\thandle @trusted {",
                _render_reverse_proxy(route, indent="\t\t"),
                "\t}",
                "\trespond 403",
                "}",
            ]
        )

    return "\n".join(
        [
            f"{route['hostname']} {{",
            _render_tls(route),
            _render_reverse_proxy(route, indent="\t"),
            "}",
        ]
    )


def _render_caddy_layer4_route(route):
    return "\n".join(
        [
            "layer4 {",
            f"\ttcp/{route['listen_address']}:{route['listen_port']} {{",
            "\t\troute {",
            f"\t\t\tproxy tcp/{route['target']}",
            "\t\t}",
            "\t}",
            "}",
        ]
    )


def _render_reverse_proxy(route, indent):
    if route.get("transport") == "tls_insecure_skip_verify":
        return "\n".join(
            [
                f"{indent}reverse_proxy {route['target']} {{",
                f"{indent}\ttransport http {{",
                f"{indent}\t\ttls_insecure_skip_verify",
                f"{indent}\t}}",
                f"{indent}}}",
            ]
        )
    return f"{indent}reverse_proxy {route['target']}"


def _render_tls(route):
    if route.get("tls") == "letsencrypt_dns":
        return "\n".join(
            [
                "\ttls {",
                "\t\tdns cloudflare {$CLOUDFLARE_API_TOKEN}",
                "\t}",
            ]
        )
    return "\ttls internal"


def _http_target(address, port):
    return f"http://{address}:{port}"


def _https_target(address, port):
    return f"https://{address}:{port}"


def _target(scheme, address, port):
    return f"{scheme}://{address}:{port}"


def _trusted_source_ranges(model):
    return list((model.globals.get("ingress") or {}).get("trusted_source_ranges") or [])


def _ingress_address(model, graph):
    vm_name = graph.service_backend_vm_name("internal-ingress")
    vm = model.vms.get(vm_name)
    if not vm:
        raise ValueError("Ingress VM internal-ingress backend is not declared")
    return _required_vm_primary_static_ipv4_address(graph, vm_name, f"Ingress VM {vm_name}")


def _required_vm_static_ipv4_address(graph, vm_name, label):
    addresses = graph.vm_static_ipv4_addresses(vm_name)
    if len(addresses) != 1:
        raise InventoryEntityGraphError(f"{label} must declare exactly one static IPv4 address")
    return addresses[0]


def _required_vm_primary_static_ipv4_address(graph, vm_name, label):
    addresses = graph.vm_static_ipv4_addresses(vm_name)
    if not addresses:
        raise InventoryEntityGraphError(f"{label} must declare at least one static IPv4 address")
    return addresses[0]


def _required_host_management_ipv4_address(graph, host_name, label):
    address = graph.host_management_ipv4_address(host_name)
    if not address:
        raise InventoryEntityGraphError(f"{label} must declare a management IPv4 address")
    return address


def _required_nas_management_ipv4_address(graph, endpoint_name, label):
    address = graph.nas_management_ipv4_address(endpoint_name)
    if not address:
        raise InventoryEntityGraphError(f"{label} must declare a management IPv4 address")
    return address
