ssh_keys:
    bootstrap:
        type: ENC[AES256_GCM,data:BWIrZjFOFk0=,iv:B3lE9hnqVwf/3nqfowLeE0niZ8lT+CQJuUYKDOlmFo4=,tag:HTqJFGl4fZGvQqEiE+e+qw==,type:str]
        created: ENC[AES256_GCM,data:RF27L/2PFIuGb0FQUEuyX8ZlxEc=,iv:gddBIncBnqaFYWtzohSwRiQ79Pv4kfPEmWIIp9JoeMo=,tag:6EdUopxZ0/VexKqKe0KMMQ==,type:time]
        public_key: ENC[AES256_GCM,data:0GX5SebC/Rg5y4/S2V3QZR7Q+2k/fACfEXd2BvBlgmD6DYlWFDHY2ngged73x/SWgMZEwfhxkEL8mZW8uC351HMaNUdFj9YdpIxAj3wjBh+ekcpwx4E72wPFIhna64PDYV7PCeUipbWqe2vwB9FATn0oJrywGcWJlGRD1EzFRsAuzq0Ae5fVGkI=,iv:AtfSkITKigSIM/YGCA3GfZsaSI9XATygHF9JMilGgPk=,tag:W+5xxC26V59dlSBFk9eCNw==,type:str]
        private_key: ENC[AES256_GCM,data:wYFPPob6IM9wYe3u5gDoDXLZXdhM3Oo6wU16sDhn8cZEbJvEA0jlKmpgtRJkGRX/IWUkjk8dVsA0CxMa2af2Scqu2/xXBVp5I3/8mZaB+1sqsYlQ+SZ0bm6XaTaErSiaZSc/NV/ymyaQdI0aW1Sa1ZIrHTefATrEAD8oWyvLSwLGMPCryiKApY2+I5bafaXiK3WV+2lpDNKLUlyvuU6w/k+QECjOA60lMzhTmGq8HL1VwpWuJRWG70Wt1IQPYZoj2BTJMKSLREXj07I1JZ37dMDMHj1XfAosQwE6x2SRAsouQnKTeRIJ3YmUGhNj4KHv0OybiMaNj7Ey8ODv+IbzoV+vX57Y86ArGVzgYfC9PpvBwVZLGrJr0R5thhIZj7Dm72LMln8qRhc2roNyX2/3DLB3He9i61nZTtPexiMtw7wKaSWKueFSRYcrosKx+DeVaT6zt0R7Fsy+/zvthdrBqkBbdsgC1qq4W+37ZsvUcLAmCfFQnleR8UErbD1RY5RLMn36Zrn5zkwcZ+phCw1bELYZyY0C6+uM7/eHvNRcXjx7zb8r3PzKe00/dWZ0xPqxE5Kh1rvzXGG5IptqgcUVj2LP4eZ4mAxr0mgrWWhc9a4=,iv:J0NxjXLGQSbPWZZk0dADXFRV/iHZ9Qod6zaPIPB8BJo=,tag:pSDEYgFzyU8Ls/ejzztOoA==,type:str]
pve_tokens:
    tofu:
        user: ENC[AES256_GCM,data:4Mz69FvtOfg=,iv:wilRZZeXKMPRKX8OTwQQ83PD48A2lo6lb++X3gr43/U=,tag:rprlf3Ph4NSIyCcHkUExNQ==,type:str]
        token_id: ENC[AES256_GCM,data:cRCzrw==,iv:FUFH5OdhiVfK/vC86wCtM6vkKpTlajf4A3Z5yp9yNAc=,tag:b7AIXpYPcndKD+xWW1eyAg==,type:str]
        value: ENC[AES256_GCM,data:UundoH0Mp9rdH0hc5jDCZ014uqGwHOgvwA8rs41wWxLDcTCV,iv:aWfvsWOscjw3HhVYHNwUEBx0M94LPrTGwyg+63RV9LY=,tag:rihzwZWJGv6Zgev1EjbWAw==,type:str]
sops:
    age:
        - recipient: age1uy27rg7l9ql0z5uze4m969sarzl3dhjlzsty9g6xsl4542kh9yzqsleu5l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQV3dyKzArUGwwQ1FWSG9n
            RXhIOVZDT2l1UzllZGhWVFkyNmZURlVhTFFnCnJFcmF1V1FCbmIyZkNSWEV6UDcv
            OGpFZXB4UDdyNStybDFzbUV3NXFsdkkKLS0tIHBGUmFNUDNRV29QT2p0dmQ1TXFw
            eWdKbkJncDEycmhOaWhYdEJTQTA4TUUKff9wylzLO1xZjQlmNesl+9Wwphd67pYe
            e25KB5/gHVC78K8vm3gubFDaUrhYHDOpOVJ3WWKQumfilHlItHTdrg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-14T22:33:29Z"
    mac: ENC[AES256_GCM,data:saM4SJiWtB0x18CqMsG4RcDRonHxNIsopjVKo/S4RMKwY7cSYLE7/Sc6gP4ayR36mMON6cMeB7WqVPnu9Xh2NE0EjaUo2rg217pIiDvw3sHRnIXPRJ7vuJRWiFDEMKR1Ehkn0EeygdyvpC/tIkYUKRYSVcx9YcPxU867PeygR4E=,iv:dglTDdNtM1DGfffuDupZnP/55CxA1ywITk4ZDumJWT0=,tag:CXsdg/9YjcKfSry2T9TPhA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
