ssh_keys:
    bootstrap:
        type: ENC[AES256_GCM,data:p/m/ckbdYKk=,iv:JFhq4Aox3CqHEs2uxp5USIt+UHk8hvjhy+RC9ZwSwhc=,tag:/oNandgvflPgA+ObxXV69g==,type:str]
        created: ENC[AES256_GCM,data:oOWZ4qbOUq7EfumO0wNWcU/jtHc=,iv:6DWiLyZw3SfDDmIqiJXKvbRyIzaH/PjbdzQk49IfsIg=,tag:cWrEx66HRfl9Dn/G/gDB1w==,type:time]
        public_key: ENC[AES256_GCM,data:cAIYBRZ5rBu4h/WgLi2oyj5GpgKt6HLjLmXL0gvLYOFkg8Q6BAeUSA/wfRN8kUCBvUeQev56hfG73v4RrWUs1P5y3MGMTyb/pxGuLFVv266X+aIeTcipUBXlaPzaq+Cbv5eK0/AOdCeWa8fb0UZWrBb79LOsoG+SXA3eZCxy/nH2GQ9pzW4n7g==,iv:B+MfoO2N0Rw7cHZ+4UVvA9h3OPnrhdJuPdZS0baXptM=,tag:HgWPxO40RiAL1vB7RRDU6g==,type:str]
        private_key: ENC[AES256_GCM,data:MGopXjuU511kQsrN8jEtFSzwBnCJ7pJK4A4aT6hdY8378cYmFW7DdZiZbCHFT/+GIxyo14cqydjvaQwGThfAidybMXe+wvfgUfC0kGkJS9Rv0L7BCDoIpzhBzKk0wTLhUGIripeL1jvyS/UyTw19v99uBdE68TrGX08zlI3qbpQojh9dgNIJG0Ll+ixxtt9IfrArXB0a2OrOjYwYYsFUxJU0OmcNRlrIk7gPbwqfDcZyzWB7WMeAGac1ubp556QVUAQoBQbB4WwbYQCysdUmg7yhV4bkQt82nm2tOHBHxxxpRhBxbKH7Xxzxfptwmsc6uiWZFO7Y2EEfn/ChmnQz9Rfatz3mFzyADc5maxKFPOQAeukCuOSi5Av6N5iFNvnzikgZMXN1jQmA94SQg5y5A+q8xyRJZleaCnHJxYI2kMVy70oJoNbVYt102mwjAvbkhKP/OtmiMNGuoR3JGjYLmXu77w9TC5sILNscgwMsPidCUk+QA1uYr/4KiOAEYY032hzAjAJIYmTREhHxG44ab8SRirbkKSxUcbdK8XjUeO5mGj3Wq87dY1ttJtyFsiQjZLXFbpq6yJtDc/QPrrg6zPw15lsraQzlwQKsZeyhAik=,iv:enBzjPKYzdLrszGOh5cSXo149R1ScEqGC849UyS/pNg=,tag:+I2J5jMWJdG9x4L0/AUlKw==,type:str]
pve_tokens:
    tofu:
        user: ENC[AES256_GCM,data:DdkPwiysdSI=,iv:Z1VHhDqj8kNLvhXGmH0QbrGF7/L2ZlaIXk33IqV/hvY=,tag:/YT7s7/XEnxFOcnuIR5nAg==,type:str]
        token_id: ENC[AES256_GCM,data:R/jTsA==,iv:HpWx6atjMQyHGXc1HLA1EWhQjQ0ec68gOQdX0mxpqJw=,tag:jf3ST6pV9wCRHyZonzhrcQ==,type:str]
        value: ENC[AES256_GCM,data:pt3x8uG0pgzQoNxl94wOvXQzeWBwjtBfnRBkhOHDt7EM3WZS,iv:lActuvjZ4ra/WZ38X19VIoKNj1A0pzVujQCHDVD8AcQ=,tag:GhBeqBHvrffgsJQaO+5jNw==,type:str]
sops:
    age:
        - recipient: age1uy27rg7l9ql0z5uze4m969sarzl3dhjlzsty9g6xsl4542kh9yzqsleu5l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUeUJrQU4wVFVmRzRXSEx1
            TC9PYjEyZkVzRlk3N1dreWxiNC9Jc0lBWFI4CkdGZFlxck16V0dTKzRIQWpicGxX
            cE13MWVmM1FsRVVpSURMbnUzVk9kUkkKLS0tIHFaVG05a1dpMnBqQUVncmUzYTRw
            WlkvaWIvWGhsYkZPZFEvcHRlb1M3YTAKBKAwdp/Jgv6B1fOQO9xMP8Ynnxegdyml
            RF/lx1gZiKOLpfOpRPNfcFt5YcAnm/faW/XsyZPjOVS1xwyuCRy1Zw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-11T04:15:50Z"
    mac: ENC[AES256_GCM,data:ZIGc5JkeYwymWfVOObzSjMqWLMafSzQdMZ7MECQ/e51Y7YGZM6kIvv96GOofnrUs4Uw08LD/ku5tjcd6aMZ3eY03wLg43c/dpgPAGEqas7o8oF3oUGCkWUDQPCX05JuIKUx55QH3lK9VI7Y9OVdr8Eupcey/ZupqfaIgW7ulL78=,iv:2vQ1+FCPneW7Z9r+h8eb+zmWZZpZIggZt1x/lXif/FY=,tag:RT8xbpZFrxs/hk3TtgLtUw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
