ssh_keys:
    bootstrap:
        type: ENC[AES256_GCM,data:aO6Jij/N,iv:fXxH5SVktNG+Hze8ARZqdhbdLFVoKlosycOHYIycHIc=,tag:MDmNW/FWHZBqWNsctySffw==,type:str]
        created: ENC[AES256_GCM,data:Swy8Q62RhkDNMnTdfFOy1VJVddE=,iv:CYO4N7NaharTWrZYx09ge9GhjoYNMlETzShTuiY2bvg=,tag:yDt0q/eMxYopQMycM//EEQ==,type:time]
        public_key: ENC[AES256_GCM,data:AVI3E2/5FxrA8DnbLIWQ73Rc8StMrQJTVeYY5kmVUilDSBwiCbQvr7J8bImlsK5zrl5Y7ns3iHWcfdcIQ6KXFIzxMw98kdahVTwnF3WBF+DJxv8flMot4TOiFaaK2HfulO2o9p87EYf41lxZ5zprFyalScqvZbbDqlqQrc0OiFzBnYFWkG+WHbw=,iv:6ojzlhJDTiaiGTyOQo2b8AVkZgKlS6WYq3B59Qmo1eA=,tag:pBKAZBalFg40UUdGI5tg1Q==,type:str]
        private_key: ENC[AES256_GCM,data:6CYH4u1BI1PytAnFrMnAVs9eVlapU2N9JaAz7lozzleeOQw3TdhK3sWv3g7EFu6l5fUnPTEjJFqf9PFs4lxSWFvMmnHRhvQ4YhlAPdAM2Z2b0tZ+24h+E6jjFvQVN6oNWarM8qnJJmsq1RW1/hikxLYMezqRGlBUdAMbjz306diEw9x67marDDTIMHj0IdNvhnkrquTuwMurqSKIBXr3hJGp4YOF70De9pHMazVLmCd/kegGDQsrFCy2LF3UHlHr4F37aw5pZFj4ZXX4ap8afeg5es/bq0BlkePT2eRipddnA1uWOlq0jLvvnxPs4y+TUtj+j5c4DdvkWKcjuTf7WlAslGed9ao9XvPXWMjlIVmhPQfhQB1tydzF8F8x4/16EihMY4eErhfDfVk3LDxd86LVT7EItmp3z2kjy1gKtfmEx5yg2V7vZ2TtJIaeNy7ORv639zE/uroC0dNaMzjdt2zsGzOJIZinhEEPmrdhalYqlRSm8B12zZ77K/hdIGD10wzoJJjkKuXkHTtG6H4QofYc+yLdm+fkqu6CpWGP/wKxfDqG0UA6l7unIgWNtbK+fGp+vyt4pre6RrP5rzIBhJ/YfYvVD8Msady55QiV8vY=,iv:6L5GCNVZMjx2Aa2Wb9q+fa4hsZsUKaGMOcST/oYTMs0=,tag:aKA+EaMijvR5Y+6pqzIewA==,type:str]
sops:
    age:
        - recipient: age1uy27rg7l9ql0z5uze4m969sarzl3dhjlzsty9g6xsl4542kh9yzqsleu5l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2ZXpvYzBTeGVncGhheC9n
            WlVENEdiTUcrNUFPV0h0eFR0TjJERmdxdVhnCkhVM1VLZHA3bjNNUGRTaVdOYnB6
            cFBETHBva09ZcGtMRzZaVWN5L3Q2aEUKLS0tIC80MWpLd0w0Ti9mTk9WbG5Da2Ft
            NUJLMTVlOWdMN3RnOFQ5ZHhHY0RScFkKYNroHHCfXfBZdgumc6w9tZ8lrw+SWSOV
            jDFU4hK4PuobgD6SErjAWVvUoNe8BQoU8ndRbVQJMhofWujPur7UTw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-15T03:21:42Z"
    mac: ENC[AES256_GCM,data:InaJ9eePRsXcw7+AZftY5vnn8XfSFRudi6I0dJCQsOQg1v808iGEZir3/3XWQJd+0pPB5gg4Lxl3OGOQSFYfOOjoenCeYbgWXtnOr0f0j4Q4JPvpj9iUTgmy9UDu2Mrg8iRWUlMWE6zo43HBDM7TQPvnkwspyloUOyM5BhLSGQ8=,iv:Wo9O2N3Lf3H9C/0bkxW/4mzUETXxIzu3lklBX9N7pVc=,tag:tNm8we0ZUytuC9j9iW6Z1A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
