from __future__ import annotations

import hashlib
import json
import shlex
from dataclasses import dataclass


REGISTRATION_WARNING = (
    "This file is automatically generated by forgejo-runner. Do not edit it manually unless you know what you are "
    "doing. Removing this file will cause act runner to re-register as a new runner."
)


@dataclass(frozen=True)
class DesiredForgejoRunnerRegistration:
    vm_name: str
    forgejo_service: str
    name: str
    scope: str
    url: str
    labels: tuple[str, ...]
    secret_identifier: str
    secret_token: str
    forgejo_backend_vm: str | None

    @property
    def cli_scope(self):
        if self.scope == "instance":
            return ""
        return self.scope


@dataclass(frozen=True)
class ObservedForgejoRunnerRegistration:
    id: int | None
    uuid: str
    name: str
    scope: str
    labels: tuple[str, ...]
    active: bool = True


@dataclass(frozen=True)
class ForgejoRunnerRegistrationAction:
    action: str
    desired: DesiredForgejoRunnerRegistration
    observed: ObservedForgejoRunnerRegistration | None = None
    reason: str = ""


@dataclass(frozen=True)
class ForgejoRunnerRegistrationPlan:
    desired: tuple[DesiredForgejoRunnerRegistration, ...]
    actions: tuple[ForgejoRunnerRegistrationAction, ...]


def desired_forgejo_runner_registrations(model):
    registrations = []
    for vm_name, vm in sorted(model.vms.items()):
        runtime = vm.get("forgejo_runner_runtime")
        if not isinstance(runtime, dict):
            continue
        forgejo_service_name = runtime.get("forgejo_service")
        forgejo_service = model.services.get(forgejo_service_name, {})
        name = f"fortress-{vm_name}"
        scope = runtime.get("scope", "instance")
        secret_identifier = _stable_secret_identifier(forgejo_service_name, vm_name, name)
        registrations.append(
            DesiredForgejoRunnerRegistration(
                vm_name=vm_name,
                forgejo_service=forgejo_service_name,
                name=name,
                scope=scope,
                url=_forgejo_root_url(forgejo_service),
                labels=tuple(runtime.get("labels") or ()),
                secret_identifier=secret_identifier,
                secret_token=_stable_secret_token(forgejo_service_name, vm_name, name),
                forgejo_backend_vm=forgejo_service.get("backend", {}).get("vm"),
            )
        )
    return tuple(registrations)


def plan_forgejo_runner_registrations(model, observed=()):
    desired = desired_forgejo_runner_registrations(model)
    observed_by_identity = {}
    for runner in observed:
        observed_by_identity.setdefault((runner.scope, runner.name), []).append(runner)

    actions = []
    for registration in desired:
        matching = observed_by_identity.get((registration.scope, registration.name), [])
        active = [runner for runner in matching if runner.active]
        if not active:
            actions.append(
                ForgejoRunnerRegistrationAction(
                    "register",
                    registration,
                    reason="no active runner exists for the declared registration identity",
                )
            )
            continue

        keeper = active[0]
        if tuple(keeper.labels) != registration.labels:
            actions.append(
                ForgejoRunnerRegistrationAction(
                    "refresh",
                    registration,
                    keeper,
                    reason="active runner labels differ from declared VM runtime intent",
                )
            )
        for duplicate in active[1:]:
            actions.append(
                ForgejoRunnerRegistrationAction(
                    "disable_duplicate",
                    registration,
                    duplicate,
                    reason=f"duplicate active runner for declared identity {registration.name}",
                )
            )
    return ForgejoRunnerRegistrationPlan(desired=desired, actions=tuple(actions))


def render_forgejo_runner_registration_command(registration, *, forgejo_binary="forgejo", secret_file=None):
    command = [
        forgejo_binary,
        "forgejo-cli",
        "actions",
        "register",
        "--name",
        registration.name,
        "--scope",
        registration.cli_scope,
        "--labels",
        ",".join(registration.labels),
    ]
    if secret_file is None:
        command.extend(["--secret", f"{registration.secret_identifier}${{FORTRESS_RUNNER_SECRET_SUFFIX}}"])
    else:
        command.extend(["--secret-file", secret_file])
    return " ".join(shlex.quote(part) for part in command)


def render_forgejo_runner_state_file(registration, *, uuid, token):
    payload = {
        "WARNING": REGISTRATION_WARNING,
        "id": 0,
        "uuid": uuid,
        "name": registration.name,
        "token": token,
        "address": registration.url,
        "labels": list(registration.labels),
    }
    return json.dumps(payload, indent=2, sort_keys=False) + "\n"


def forgejo_runner_registration_vars(registration):
    return {
        "vm_name": registration.vm_name,
        "forgejo_service": registration.forgejo_service,
        "forgejo_backend_vm": registration.forgejo_backend_vm,
        "name": registration.name,
        "scope": registration.scope,
        "cli_scope": registration.cli_scope,
        "url": registration.url,
        "labels": list(registration.labels),
        "secret_identifier": registration.secret_identifier,
        "secret_token": registration.secret_token,
    }


def render_forgejo_runner_convergence_script(
    registration,
    *,
    forgejo_binary="forgejo",
    secret_file,
    runner_state_file,
):
    command = render_forgejo_runner_registration_command(
        registration,
        forgejo_binary=forgejo_binary,
        secret_file=secret_file,
    )
    labels_json = json.dumps(list(registration.labels))
    warning_json = json.dumps(REGISTRATION_WARNING)
    return (
        "#!/usr/bin/env bash\n"
        "set -euo pipefail\n"
        f"token=$(tr -d '\\n' < {shlex.quote(secret_file)})\n"
        f"if ! [[ \"$token\" =~ ^{registration.secret_identifier}[0-9a-f]{{24}}$ ]]; then\n"
        f"  echo 'runner secret must be 40 lowercase hex characters beginning with {registration.secret_identifier}' >&2\n"
        "  exit 1\n"
        "fi\n"
        f"uuid=$({command})\n"
        f"install -d -m 0750 {shlex.quote(runner_state_file.rsplit('/', 1)[0])}\n"
        f"python3 - {shlex.quote(runner_state_file)} \"$uuid\" \"$token\" <<'PY'\n"
        "import json\n"
        "import sys\n"
        "path, uuid, token = sys.argv[1:]\n"
        "payload = {\n"
        f"    \"WARNING\": {warning_json},\n"
        "    \"id\": 0,\n"
        f"    \"name\": {json.dumps(registration.name)},\n"
        "    \"uuid\": uuid,\n"
        "    \"token\": token,\n"
        f"    \"address\": {json.dumps(registration.url)},\n"
        f"    \"labels\": {labels_json},\n"
        "}\n"
        "with open(path, \"w\") as handle:\n"
        "    json.dump(payload, handle, indent=2)\n"
        "    handle.write(\"\\n\")\n"
        "PY\n"
    )


def _stable_secret_identifier(forgejo_service_name, vm_name, runner_name):
    seed = f"fortress:forgejo-runner-registration:{forgejo_service_name}:{vm_name}:{runner_name}"
    return hashlib.sha256(seed.encode()).hexdigest()[:16]


def _stable_secret_token(forgejo_service_name, vm_name, runner_name):
    seed = f"fortress:forgejo-runner-registration-secret:{forgejo_service_name}:{vm_name}:{runner_name}"
    return _stable_secret_identifier(forgejo_service_name, vm_name, runner_name) + hashlib.sha256(seed.encode()).hexdigest()[:24]


def _forgejo_root_url(service):
    for container in service.get("deploy", {}).get("containers", []) or []:
        root_url = (container.get("env") or {}).get("FORGEJO__server__ROOT_URL")
        if root_url:
            return root_url
    for route in service.get("ingress_routes", []) or []:
        hostname = route.get("hostname")
        if hostname:
            return f"https://{hostname}/"
    return ""
