name: forgejo
service_data_owner:
  uid: 1000
  gid: 1000
backend:
  vm: forgejo-vm
ingress_routes:
  - name: web
    hostname: git.fearn.cloud
    published_port: 3000
    exposure: lan_only
    tls: letsencrypt_dns
    auth:
      type: none
    directory_entry:
      enabled: true
      label: Forgejo
      group: Development
ingress_tcp_routes:
  - name: ssh
    hostname: git.fearn.cloud
    listen_address: 10.40.0.21
    listen_port: 22
    published_port: 2222
deploy:
  type: quadlet
  containers:
    - name: server
      image: codeberg.org/forgejo/forgejo:15.0.3
      published_ports:
        - bind: 0.0.0.0
          host: 3000
          container: 3000
        - bind: 0.0.0.0
          host: 2222
          container: 22
      env:
        USER_UID: 1000
        USER_GID: 1000
        FORGEJO__server__DOMAIN: git.fearn.cloud
        FORGEJO__server__ROOT_URL: https://git.fearn.cloud/
        FORGEJO__server__SSH_DOMAIN: git.fearn.cloud
        FORGEJO__server__SSH_PORT: 22
      volumes:
        - service_path: data
          container: /data
          access: read_write
