---
- name: Read declared PVE users
  ansible.builtin.set_fact:
    proxmox_users_declared: "{{ fortress_host.proxmox.users | default([]) }}"
  changed_when: false

- name: Ensure declared PVE users exist
  ansible.builtin.command:
    cmd: "pveum user add {{ item.name }}"
  register: proxmox_users_add
  changed_when: proxmox_users_add.rc == 0
  failed_when:
    - proxmox_users_add.rc != 0
    - "'already exists' not in proxmox_users_add.stderr"
  loop: "{{ proxmox_users_declared }}"

- name: Ensure declared PVE user roles exist on root ACL
  ansible.builtin.command:
    cmd: "pveum aclmod / -user {{ item.0.name }} -role {{ item.1 }}"
  changed_when: false
  loop: "{{ proxmox_users_declared | subelements('roles', skip_missing=True) }}"
